name: fsl-notebook

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - matplotlib>=3.7.0
  - scikit-learn>=1.2.0
  - numpy>=1.24.0,<2.0.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - pip

